<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="publish"
    nsURI="http://com.cloudsmith.publish/1.0" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Publishable" abstract="true" interface="true"
      eSuperTypes="../../org.eclipse.b3.build/model/B3Build.ecore#//BuildUnit">
    <eOperations name="publish" eType="ecore:EDataType ../../org.eclipse.b3.build/model/B3Build.ecore#//B3BuilderJob"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RPM" abstract="true" interface="true"
      eSuperTypes="#//Publishable"/>
  <eClassifiers xsi:type="ecore:EClass" name="GEM" abstract="true" interface="true"
      eSuperTypes="#//Publishable"/>
  <eClassifiers xsi:type="ecore:EClass" name="NativeActions" eSuperTypes="#//ActionPackage #//INativeActions"/>
  <eClassifiers xsi:type="ecore:EClass" name="IRPMActions" abstract="true" interface="true">
    <eOperations name="installSRCRPM" eType="#//PublisherAction"/>
    <eOperations name="uninstallSRCRPM" eType="#//PublisherAction"/>
    <eOperations name="installRPM" eType="#//PublisherAction"/>
    <eOperations name="uninstallRPM" eType="#//PublisherAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GEMActions" eSuperTypes="#//ActionPackage #//IGEMActions"/>
  <eClassifiers xsi:type="ecore:EClass" name="Publisher" eSuperTypes="#//INativeActions">
    <eOperations name="write" eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//BuildSet">
      <eParameters name="unit" eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//BuildUnit"/>
    </eOperations>
    <eOperations name="write" eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//BuildSet">
      <eParameters name="unit" eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//BuildUnit"/>
      <eParameters name="data" eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//BuildSet"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="singleton" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType ../../org.eclipse.b3.build/model/B3Build.ecore#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copyrightText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copyrightURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="licenseText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="licenseURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runtimeFilter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="properties">
      <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.b3.p2/model/p2.ecore#//Map">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenInstalling" upperBound="-1"
        eType="#//PublisherAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenUninstalling" upperBound="-1"
        eType="#//PublisherAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenConfiguring" upperBound="-1"
        eType="#//PublisherAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenUnconfiguring" upperBound="-1"
        eType="#//PublisherAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//BuildUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provides" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//Capability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//RequiredCapability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaRequires" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//RequiredCapability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedPackages" upperBound="-1"
        eType="#//ActionPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nativeActions" eType="#//NativeActions"
        changeable="false" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublisherAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ActionParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionPackage" lowerBound="1"
        eType="#//ActionPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionPackage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="touchPoint" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="INativeActions" abstract="true" interface="true">
    <eOperations name="link" eType="#//PublisherAction">
      <eParameters name="targetDir" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="linkTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="linkName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="force" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="unZip" eType="#//PublisherAction">
      <eParameters name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="cleanupZip" eType="#//PublisherAction">
      <eParameters name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="copy" eType="#//PublisherAction">
      <eParameters name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="overwrite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="cleanupCopy" eType="#//PublisherAction">
      <eParameters name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="mkdir" eType="#//PublisherAction">
      <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="rmdir" eType="#//PublisherAction">
      <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="remove" eType="#//PublisherAction">
      <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="chmod" eType="#//PublisherAction">
      <eParameters name="targetDir" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="targetFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="permissions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="options" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RPMActions" eSuperTypes="#//ActionPackage #//IRPMActions"/>
  <eClassifiers xsi:type="ecore:EClass" name="RPMPublisher" eSuperTypes="#//Publisher #//IRPMActions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RPMInstallDir" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rpmActions" eType="#//RPMActions"
        changeable="false" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IGEMActions" abstract="true" interface="true">
    <eOperations name="installGEM" eType="#//PublisherAction"/>
    <eOperations name="uninstallGEM" eType="#//PublisherAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GEMPublisher" eSuperTypes="#//Publisher #//IGEMActions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gemActions" eType="#//GEMActions"
        changeable="false" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryDefinition" abstract="true"
      interface="true" eSuperTypes="#//Publishable"/>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryPublisher">
    <eOperations name="write" eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//BuildSet">
      <eParameters name="unit" eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//BuildUnit"/>
      <eParameters name="output" eType="ecore:EClass ../../org.eclipse.b3.build/model/B3Build.ecore#//BuildSet"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RubyPublisher" eSuperTypes="#//Publisher #//IRubyActions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rubyActions" eType="#//RubyActions"
        changeable="false" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IRubyActions" abstract="true" interface="true">
    <eOperations name="installRubyEnterpriseFromCSource" eType="#//PublisherAction"/>
    <eOperations name="uninstallRubyEnterpriseFromCSource" eType="#//PublisherAction"/>
    <eOperations name="installPassenger" eType="#//PublisherAction">
      <eParameters name="server" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="uninstallPassenger" eType="#//PublisherAction">
      <eParameters name="server" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RubyActions" eSuperTypes="#//ActionPackage #//IRubyActions"/>
  <eClassifiers xsi:type="ecore:EClass" name="RubyRuntime" abstract="true" interface="true"
      eSuperTypes="#//Publishable"/>
  <eClassifiers xsi:type="ecore:EClass" name="CSource" abstract="true" interface="true"
      eSuperTypes="../../org.eclipse.b3.build/model/B3Build.ecore#//BuildUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="IExtNativeActions" abstract="true" interface="true">
    <eOperations name="installFromCSource" eType="#//PublisherAction"/>
    <eOperations name="uninstallFromCSource" eType="#//PublisherAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtNativeActions" eSuperTypes="#//ActionPackage #//IExtNativeActions"/>
  <eClassifiers xsi:type="ecore:EClass" name="NativePublisher" eSuperTypes="#//Publisher #//IExtNativeActions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extNativeActions" eType="#//ExtNativeActions"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Native" abstract="true" interface="true"
      eSuperTypes="#//Publishable"/>
</ecore:EPackage>
